import { useState } from 'react'
import { Download, FolderOpen, Play, RefreshCcw, Trash2 } from 'lucide-react'
import type { BatchRecord, JobDetail, JobRecord } from '../../../shared/types'
import { useAppStore } from '../store'
import { Badge, Button, Card } from '../components/ui'
import { ExportPanel } from '../components/ExportPanel'

function tone(status:JobRecord['status']):'neutral'|'success'|'warn'|'error'|'info'{if(status==='completed')return'success';if(status==='completed_with_errors')return'warn';if(status==='failed')return'error';if(['discovering','scraping','validating','comparing'].includes(status))return'info';if(['paused','cancelled','interrupted'].includes(status))return'warn';return'neutral'}
export function HistoryPage({onOpenJob}:{onOpenJob:()=>void}){
  const jobs=useAppStore((s)=>s.jobs);const batches=useAppStore((s)=>s.batches);const setJobs=useAppStore((s)=>s.setJobs);const setBatches=useAppStore((s)=>s.setBatches);const setActiveDetail=useAppStore((s)=>s.setActiveDetail);const settings=useAppStore((s)=>s.settings)
  const[exportJob,setExportJob]=useState<JobRecord|null>(null);const[error,setError]=useState('')
  async function refresh(){try{const[j,b]=await Promise.all([window.aventics.request<JobRecord[]>({type:'listJobs'}),window.aventics.request<BatchRecord[]>({type:'listBatches'})]);setJobs(j);setBatches(b)}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function open(job:JobRecord){try{setActiveDetail(await window.aventics.request<JobDetail>({type:'getJob',jobId:job.id}));onOpenJob()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function resume(job:JobRecord){if(!settings)return;try{await window.aventics.request({type:'resume',jobId:job.id,headless:settings.headless});await open(job)}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function remove(job:JobRecord){if(!confirm(`Delete job "${job.seriesName}" from the local database? Exported files are not deleted.`))return;try{await window.aventics.request({type:'deleteJob',jobId:job.id});await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  return <div className="space-y-5"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-semibold text-slate-950">History</h1><p className="mt-1 text-sm text-slate-500">Persistent scrape jobs, batches, comparison state and exports.</p></div><Button variant="secondary" onClick={refresh}><RefreshCcw size={15}/>Refresh</Button></div>{error&&<div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}
    {batches.length>0&&<Card className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4 font-medium">Batches</div><div className="overflow-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Batch</th><th className="px-4 py-3">Series</th><th className="px-4 py-3">Products</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Created</th></tr></thead><tbody className="divide-y divide-slate-100">{batches.map((b)=><tr key={b.id}><td className="px-4 py-3 font-medium">{b.name}</td><td className="px-4 py-3">{b.completedJobs}/{b.jobCount}</td><td className="px-4 py-3">{b.completedProducts}/{b.totalProducts}</td><td className="px-4 py-3"><Badge tone={b.status==='completed'?'success':b.status==='completed_with_errors'?'warn':b.status==='running'?'info':'neutral'}>{b.status.replaceAll('_',' ')}</Badge></td><td className="px-4 py-3 text-slate-500">{new Date(b.createdAt).toLocaleString()}</td></tr>)}</tbody></table></div></Card>}
    <Card className="overflow-hidden"><div className="border-b border-slate-200 px-5 py-4 font-medium">Jobs</div><div className="overflow-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">Series</th><th className="px-4 py-3">Products</th><th className="px-4 py-3">Complete</th><th className="px-4 py-3">Incomplete</th><th className="px-4 py-3">Failed</th><th className="px-4 py-3">Comparison</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Date</th><th className="px-4 py-3"></th></tr></thead><tbody className="divide-y divide-slate-100">{jobs.map((job)=><tr key={job.id}><td className="px-4 py-3"><button className="font-medium text-slate-900 hover:underline" onClick={()=>open(job)}>{job.seriesName}</button><div className="mt-1 max-w-[260px] truncate text-xs text-slate-400">{job.sourceUrl}</div></td><td className="px-4 py-3 tabular-nums">{job.productCount}</td><td className="px-4 py-3 text-emerald-700">{Math.max(0,job.completedCount-job.incompleteCount)}</td><td className="px-4 py-3 text-amber-700">{job.incompleteCount}</td><td className="px-4 py-3 text-red-700">{job.failedCount}</td><td className="px-4 py-3 text-xs text-slate-500">{job.comparedToJobId?'Compared':'—'}</td><td className="px-4 py-3"><Badge tone={tone(job.status)}>{job.status.replaceAll('_',' ')}</Badge></td><td className="px-4 py-3 text-xs text-slate-500">{new Date(job.createdAt).toLocaleString()}</td><td className="px-4 py-3"><div className="flex justify-end gap-1">{['paused','cancelled','interrupted'].includes(job.status)&&<Button variant="ghost" title="Resume" onClick={()=>resume(job)}><Play size={15}/></Button>}<Button variant="ghost" title="Export" onClick={()=>setExportJob(job)}><Download size={15}/></Button>{job.outputPath&&<Button variant="ghost" title="Open output" onClick={()=>window.aventics.openPath(job.outputPath!)}><FolderOpen size={15}/></Button>}<Button variant="ghost" title="Delete" onClick={()=>remove(job)}><Trash2 size={15}/></Button></div></td></tr>)}{jobs.length===0&&<tr><td colSpan={9} className="px-5 py-12 text-center text-slate-400">No jobs yet.</td></tr>}</tbody></table></div></Card>{exportJob&&<ExportPanel job={exportJob} onClose={()=>setExportJob(null)}/>}</div>
}
