import type { ReactNode } from 'react'
import { useEffect, useMemo, useState } from 'react'
import { ExternalLink, RefreshCcw, Search, X } from 'lucide-react'
import type { ProductQuery, ProductQueryResult, ProductRecord, QualityStatus, ChangeStatus } from '../../../shared/types'
import { useAppStore } from '../store'
import { Badge, Button, Card, Input } from '../components/ui'

function qualityTone(status:ProductRecord['quality']['status']):'neutral'|'success'|'warn'|'error'{if(status==='complete')return'success';if(status==='incomplete')return'warn';if(status==='failed')return'error';return'neutral'}
function changeTone(status:ProductRecord['changeStatus']):'neutral'|'success'|'warn'|'info'{if(status==='added')return'success';if(status==='changed')return'warn';if(status==='unchanged')return'neutral';return'info'}

export function ProductsPage(){
  const jobs=useAppStore((s)=>s.jobs)
  const series=useMemo(()=>Array.from(new Set(jobs.map((j)=>j.seriesName))).sort(),[jobs])
  const[result,setResult]=useState<ProductQueryResult>({products:[],total:0})
  const[query,setQuery]=useState<ProductQuery>({quality:'all',change:'all',limit:500,offset:0})
  const[selected,setSelected]=useState<ProductRecord|null>(null)
  const[busy,setBusy]=useState(false);const[error,setError]=useState('')
  async function load(next=query){setBusy(true);setError('');try{const r=await window.aventics.request<ProductQueryResult>({type:'queryProducts',query:next});setResult(r);if(selected){const fresh=r.products.find((p)=>p.id===selected.id);if(fresh)setSelected(fresh)}}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  useEffect(()=>{void load()},[])
  function patch(p:Partial<ProductQuery>){const n={...query,...p,offset:0};setQuery(n);void load(n)}
  return <div className="space-y-5"><div><h1 className="text-2xl font-semibold text-slate-950">Products</h1><p className="mt-1 text-sm text-slate-500">Browse scraped catalog data, quality results, assets and changes across jobs.</p></div>
    <Card className="p-4"><div className="grid gap-3 lg:grid-cols-[1fr_220px_170px_170px_auto]"><div className="relative"><Search size={15} className="absolute left-3 top-3 text-slate-400"/><Input className="pl-9" value={query.search??''} onChange={(e)=>setQuery({...query,search:e.target.value})} onKeyDown={(e)=>{if(e.key==='Enter')void load()}} placeholder="Search SKU, name or description"/></div><select className="h-10 rounded-md border border-slate-300 bg-white px-2 text-sm" value={query.series??''} onChange={(e)=>patch({series:e.target.value||undefined})}><option value="">All series</option>{series.map((x)=><option key={x}>{x}</option>)}</select><select className="h-10 rounded-md border border-slate-300 bg-white px-2 text-sm" value={query.quality??'all'} onChange={(e)=>patch({quality:e.target.value as QualityStatus|'all'})}><option value="all">All quality</option><option value="complete">Complete</option><option value="incomplete">Incomplete</option><option value="failed">Failed</option><option value="not_evaluated">Not evaluated</option></select><select className="h-10 rounded-md border border-slate-300 bg-white px-2 text-sm" value={query.change??'all'} onChange={(e)=>patch({change:e.target.value as ChangeStatus|'all'})}><option value="all">All changes</option><option value="added">Added</option><option value="changed">Changed</option><option value="unchanged">Unchanged</option><option value="not_compared">Not compared</option></select><Button variant="secondary" onClick={()=>load()} disabled={busy}><RefreshCcw size={15}/>{busy?'Loading':'Refresh'}</Button></div>
      <div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-600"><label><input type="checkbox" checked={query.hasImage===true} onChange={(e)=>patch({hasImage:e.target.checked?true:null})}/> Has image</label><label><input type="checkbox" checked={query.hasDocument===true} onChange={(e)=>patch({hasDocument:e.target.checked?true:null})}/> Has document</label><label><input type="checkbox" checked={query.hasCad===true} onChange={(e)=>patch({hasCad:e.target.checked?true:null})}/> Has CAD</label><span className="ml-auto tabular-nums">Showing {result.products.length.toLocaleString()} of {result.total.toLocaleString()}</span></div></Card>
    {error&&<div className="rounded-lg border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">{error}</div>}
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_420px]"><Card className="overflow-hidden"><div className="overflow-auto"><table className="w-full text-left text-sm"><thead className="sticky top-0 bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">SKU</th><th className="px-4 py-3">Product</th><th className="px-4 py-3">Specs</th><th className="px-4 py-3">Assets</th><th className="px-4 py-3">Quality</th><th className="px-4 py-3">Change</th></tr></thead><tbody className="divide-y divide-slate-100">{result.products.map((p)=><tr key={p.id} className={`cursor-pointer hover:bg-slate-50 ${selected?.id===p.id?'bg-slate-50':''}`} onClick={()=>setSelected(p)}><td className="px-4 py-3 font-medium text-slate-900">{p.sku}</td><td className="max-w-[360px] px-4 py-3"><div className="truncate">{p.name||'—'}</div><div className="mt-1 truncate text-xs text-slate-400">{p.url}</div></td><td className="px-4 py-3 tabular-nums">{Object.keys(p.specifications).length}</td><td className="px-4 py-3 tabular-nums">{p.assets.length}</td><td className="px-4 py-3"><Badge tone={qualityTone(p.quality.status)}>{p.quality.status.replace('_',' ')}</Badge></td><td className="px-4 py-3"><Badge tone={changeTone(p.changeStatus)}>{p.changeStatus.replace('_',' ')}</Badge></td></tr>)}{!result.products.length&&<tr><td colSpan={6} className="px-4 py-12 text-center text-slate-400">No products match these filters.</td></tr>}</tbody></table></div></Card>
      <Card className="min-h-[520px] p-5">{selected?<ProductDetail product={selected} onClose={()=>setSelected(null)}/>:<div className="flex h-full min-h-[460px] items-center justify-center text-sm text-slate-400">Select a product to inspect details.</div>}</Card></div>
  </div>
}
function ProductDetail({product,onClose}:{product:ProductRecord;onClose:()=>void}){return <div><div className="flex items-start justify-between gap-3"><div><div className="text-xs font-semibold uppercase tracking-wide text-slate-500">{product.sku}</div><h2 className="mt-1 font-semibold text-slate-950">{product.name||'Unnamed product'}</h2></div><Button variant="ghost" onClick={onClose}><X size={16}/></Button></div><div className="mt-3 flex gap-2"><Badge tone={qualityTone(product.quality.status)}>{product.quality.status} · {product.quality.score}%</Badge><Badge tone={changeTone(product.changeStatus)}>{product.changeStatus}</Badge></div>
  {product.description&&<p className="mt-4 text-xs leading-5 text-slate-600">{product.description}</p>}
  <Section title={`Specifications (${Object.keys(product.specifications).length})`}><div className="max-h-64 overflow-auto divide-y divide-slate-100">{Object.entries(product.specifications).map(([k,v])=><div key={k} className="grid grid-cols-[42%_1fr] gap-3 py-2 text-xs"><div className="text-slate-500">{k}</div><div className="font-medium text-slate-800">{v}</div></div>)}</div></Section>
  <Section title={`Assets (${product.assets.length})`}><div className="space-y-2">{product.assets.map((a)=><button key={a.id} className="flex w-full items-center justify-between gap-2 rounded-md border border-slate-200 px-3 py-2 text-left text-xs hover:bg-slate-50" onClick={()=>window.aventics.openExternal(a.url)}><div className="min-w-0"><div className="font-medium text-slate-800">{a.title||a.category}</div><div className="truncate text-slate-400">{a.type} · {a.format||a.category}</div></div><ExternalLink size={14} className="shrink-0 text-slate-400"/></button>)}{!product.assets.length&&<div className="text-xs text-slate-400">No asset links detected.</div>}</div></Section>
  {product.quality.issues.length>0&&<Section title="Quality notes"><div className="space-y-2">{product.quality.issues.map((i)=><div key={`${i.code}-${i.message}`} className="text-xs text-slate-600"><span className="font-medium">{i.code}</span> — {i.message}</div>)}</div></Section>}
  <button className="mt-4 flex items-center gap-2 text-xs font-medium text-slate-700 hover:underline" onClick={()=>window.aventics.openExternal(product.url)}>Open product page <ExternalLink size={13}/></button></div>}
function Section({title,children}:{title:string;children:ReactNode}){return <div className="mt-5"><div className="mb-2 text-xs font-semibold uppercase tracking-wide text-slate-500">{title}</div>{children}</div>}
