import type { ReactNode } from 'react'
import { useEffect, useState } from 'react'
import { FolderOpen, Save } from 'lucide-react'
import type { AppSettings } from '../../../shared/types'
import { useAppStore } from '../store'
import { Button, Card, Input } from '../components/ui'
export function SettingsPage(){
  const stored=useAppStore((s)=>s.settings);const setStored=useAppStore((s)=>s.setSettings);const[form,setForm]=useState<AppSettings|null>(stored);const[message,setMessage]=useState('')
  useEffect(()=>setForm(stored),[stored]);if(!form)return<div className="text-sm text-slate-500">Loading settings…</div>
  async function choose(){const p=await window.aventics.chooseOutputDirectory();if(p)setForm({...form!,outputDirectory:p})}
  async function save(){try{const next=await window.aventics.setSettings(form!);setStored(next);setMessage('Settings saved.');setTimeout(()=>setMessage(''),2500)}catch(e){setMessage(e instanceof Error?e.message:String(e))}}
  return <div className="max-w-4xl space-y-5"><div><h1 className="text-2xl font-semibold text-slate-950">Settings</h1><p className="mt-1 text-sm text-slate-500">Defaults for new jobs, asset extraction, validation and comparison.</p></div><Card className="space-y-5 p-5"><Field label="Output directory" help="Excel/CSV/JSON exports are written here. The SQLite database stays in the app data folder."><div className="flex gap-2"><Input value={form.outputDirectory} onChange={(e)=>setForm({...form,outputDirectory:e.target.value})}/><Button variant="secondary" onClick={choose}><FolderOpen size={15}/>Browse</Button></div></Field><div className="grid gap-5 sm:grid-cols-3"><Field label="HTTP concurrency" help="Recommended 4–8; maximum 10."><Input type="number" min={1} max={10} value={form.concurrency} onChange={(e)=>setForm({...form,concurrency:Number(e.target.value)})}/></Field><Field label="Retry attempts" help="Per product before failure."><Input type="number" min={1} max={6} value={form.retryAttempts} onChange={(e)=>setForm({...form,retryAttempts:Number(e.target.value)})}/></Field><Field label="Request timeout (ms)" help="Per product request."><Input type="number" min={5000} max={120000} step={1000} value={form.timeoutMs} onChange={(e)=>setForm({...form,timeoutMs:Number(e.target.value)})}/></Field></div><Field label="Browser" help="Uses installed Microsoft Edge through Playwright; no extra Chromium download is required."><Input value="Microsoft Edge (msedge)" disabled/></Field><div className="grid gap-3 md:grid-cols-2"><Check label="Run Edge headless" checked={form.headless} onChange={(v)=>setForm({...form,headless:v})}/><Check label="Auto-compare with previous completed scrape" checked={form.autoCompare} onChange={(v)=>setForm({...form,autoCompare:v})}/><Check label="Run data-quality validation" checked={form.runQualityValidation} onChange={(v)=>setForm({...form,runQualityValidation:v})}/><Check label="Extract product image links" checked={form.extractImages} onChange={(v)=>setForm({...form,extractImages:v})}/><Check label="Extract document / datasheet links" checked={form.extractDocuments} onChange={(v)=>setForm({...form,extractDocuments:v})}/><Check label="Extract CAD links" checked={form.extractCad} onChange={(v)=>setForm({...form,extractCad:v})}/><Check label="Developer diagnostics in logs" checked={form.developerDiagnostics} onChange={(v)=>setForm({...form,developerDiagnostics:v})}/></div><div className="flex items-center gap-3 border-t border-slate-200 pt-5"><Button onClick={save}><Save size={15}/>Save settings</Button>{message&&<span className="text-sm text-slate-500">{message}</span>}</div></Card></div>
}
function Field({label,help,children}:{label:string;help:string;children:ReactNode}){return <div><label className="mb-2 block text-sm font-medium text-slate-800">{label}</label>{children}<p className="mt-1.5 text-xs leading-5 text-slate-400">{help}</p></div>}
function Check({label,checked,onChange}:{label:string;checked:boolean;onChange:(v:boolean)=>void}){return <label className="flex items-center gap-3 rounded-lg border border-slate-200 px-3 py-3 text-sm text-slate-700"><input type="checkbox" checked={checked} onChange={(e)=>onChange(e.target.checked)}/>{label}</label>}
